config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  
  namespace :admin do
    
    root 'welcome#index'
     
    resources :collection_photos do 
                 collection do
                   get 'archive' => 'collection_photos#index_archive' 
                   get 'edit_batch' => 'collection_photos#edit_batch' 
                   put 'edit_batch' => 'collection_photos#update_batch'  
                 end
              end
    resources :collection_views, :collection_tags
  end
  
  

end

app/controllers/admin/collection_views_controller.rb
class Admin::CollectionViewsController < ApplicationController

# Each collection_view shows collection_photos 
# that are tagged with associated collection_tag records

# GET 'admin/collection_views'
def index
  @views = CollectionView.all
end

#GET '/admin/collection_views/new'
def new

@TYPES = CollectionView.types

end

# POST '/admin/collection_views'
def create

  view = CollectionView.new(view_params)
  view.save
  redirect_to admin_collection_views_path 
  
end
 

# GET admin/collection_views/:id/edit 
def edit

  @TYPES = CollectionView.types
  @view = set_view
  @tags = @view.collection_tags
  @available_tags = CollectionTag.all
  
end

# PATCH/PUT 'admin/collection_views/:id/edit'
def update

this_view = set_view

# three separate actions:
  
  if params[:add_tags_ids]   
    
    tags_to_append = CollectionTag.find(params[:add_tags_ids]) 
    
    tags_to_append.each do |tag|  
      if !this_view.collection_tags.exists?(tag.id)
       this_view.collection_tags<< tag
      end 
    end  
  end
  
  if params[:delete_tags_ids] 
    
    tags_to_delete = this_view.collection_tags.find(params[:delete_tags_ids])
    
    tags_to_delete.each { |tag| this_view.collection_tags.destroy(tag) }
    
  end

  if params[:collection_view] # last, set name and type:
    
      
    this_view.name = params[:collection_view][:name]
    this_view.view_type = params[:collection_view][:view_type]
    
    this_view.save!  
  end
  
  redirect_to edit_admin_collection_view_path(this_view)
end

# GET 'admin/collection_views/:id'
def show
 
 @this_view = set_view
 @photos = @this_view.photos
  
end

# DELETE /admin/collection_views/:id
def destroy

this_view = set_view

# callback to clear associated collection_tags
#             from the join table
this_view.destroy

redirect_to admin_collection_views_path
end

private

# whitelists attributes
def view_params 
  
  params.require(:collection_view).permit(:name,:view_type)
  
end

# callbacks for shared resources across actions
def set_view
  CollectionView.find(params[:id])
end

end

app/controllers/collection_views_controller.rb
class CollectionViewsController < ApplicationController

# Each view shows photos tagged under associated tags

def index

  @views = CollectionView.all
end

#GET /collection_views/new
def new

#collapse to index
#redirect_to collection_views_path

end


# POST /collection_views
def create

  view = CollectionView.new(view_params)
  view.save
  redirect_to collection_views_path 

end
 

# GET collection_views/:id/edit 
def edit

  @TYPES = CollectionView.view_types
  @view = set_view
  @tags = @view.collection_tags
  @available_tags = CollectionTag.all
  
end

# PATCH/PUT collection_views/:id/edit
def update

this_view = set_view

# three separate actions:
  
  if params[:add_tags_ids]   
    
    tags_to_append = CollectionTag.find(params[:add_tags_ids]) 
    tags_to_append.each do |tag|
      
      if !this_view.collection_tags.exists?(tag.id)
      this_view.collection_tags<< tag
      end 
    
    end
    
  end
  
  if params[:delete_tags_ids] 
    
    tags_to_delete = this_view.collection_tags.find(params[:delete_tags_ids])
    
    tags_to_delete.each { |tag| this_view.collection_tags.destroy(tag) }
    
  end

  if params[:collection_view] # else sets the type of the view
    
      
    this_view.name = params[:collection_view][:name]  
   
    if params[:view_type] 

      this_view.view_type = params[:view_type] 
    end  

    this_view.save!
    
  end
  
  redirect_to edit_collection_view_path(this_view)
 
#render plain: params.inspect
end

# GET collection_views/:id
def show
 
 @this_view = set_view
 
 keywords = []
 @this_view.collection_tags.each {  |tag| keywords<< tag.keyword }
 
 @photos = CollectionPhoto.tagged_with(keywords, :on => :keywords, :any => true)
  
  #render plain: @photos.each {|photo| puts photo.name}
  #render plain: keywords.inspect
end


def destroy

end

private

# whitelists attributes
def view_params 
  
  params.require(:collection_view).permit(:name,:type_view)
  
end

# callbacks for shared resources across actions
def set_view
  CollectionView.find(params[:id])
end

end

app/helpers/collection_views_helper.rb
module CollectionViewsHelper
end

app/views/admin/collection_views/edit.html.erb
<!DOCTYPE html>
<html>

<head>
<style>
.column-left{ float: left; width: 33%; }
.column-right{ float: right; width: 33%; }
.column-center{ display: inline-block; width: 33%; }

#properties{
              border:2px solid #009900;
              float:left;
              top: 20px;
              height:400px;
              width:33%;
              clear:left;
}

#delete_keywords{
           border: 2px solid #0000FF;
           width:33%;
           height:400px;
           float:right;
           overflow-y:scroll; 
}
#add_keywords{
           border: 2px solid #0000FF;
           width:33%;
           height:400px;
           float:right;
           overflow-y:scroll;
}
#submit{
        width:100%;  
        text-align:right;
        margin-bottom:10px;
        margin-top:10px; 
        clear:both}

</style>
</head>


<body>

<h1><center> Edit: <%= @view.name%> </center></h1>
<%= link_to 'Index of Views', admin_collection_views_path %>
<br><br>

<%= form_for @view, url: admin_collection_view_path(@view), method: :patch  do |f| %>

 
     <div id="submit">
       <%= f.submit "Edit view"%>
     </div>
 
     <div id="delete_keywords">
        <h3><center>Seleccionar keywords para BORRAR:</center></h4>
       <br><br>
      
         <% if @tags.empty? %>  <center>No hay keywords en esta vista</center>
         <% else %> 
	   
              <% @tags.each do |tag| %>
	         <ul>
		 <%= check_box_tag 'delete_tags_ids[]', tag.id -%>
		 <%= tag.keyword %>
		 </ul>  
		 <br>
              <% end %>
	  
       <% end %>
   
     </div>
   
     <div id="properties">
       <br>
       <%= f.label :name  %>
        <%= f.text_field :name %>
	<br>
	<br>
	<%= f.label 'Tipo de vista:' %>
	<%= f.select :view_type, @TYPES %>
	 
     </div>
   
     <div id="add_keywords">
       <h3><center>Seleccionar keywords para ANADIR</center></h3> 
       
       <% if @available_tags.empty? %> No keywords known
       
       <% else %>
      
          
          <% @available_tags.each do |tag| %>
	      <ul>
		<%= check_box_tag 'add_tags_ids[]', tag.id -%>
		<%= tag.keyword -%>
	      </ul>
	      <% end %> 
         
	 <% end %>
     </div>
     
<% end %>

</body>
</html>

app/views/admin/collection_views/index.html.erb
<head>
<style>

.view{
      clear:both;
      height:100%;
      width:100%;
      margin-bottom: 500px;
}

.view_header{
     clear:both;
     background-color: #0099CC;
}

.photos_view{
              border:2px solid #009900;
              float:left;
              margin-right:10px;
              top: 20px;
              height:400px;
              width:30%;
              overflow-y:scroll;
              clear:left
}
.photos_view img {
   width: 100%;
}

.view_properties{
                 width:50%;
                 float:right;
                 height:400px;
}

.button_frame{
            border: 2px solid #0000FF; 
            margin-bottom:10px;
            float:left;
            clear:both <!-- clear  !-->
}

</style>
</head>

<body>

<%= link_to 'Vuelta a Admin', admin_root_path %>
<br>
<h1><center>Indice de Vistas</center></h1>

<div class="button_frame">
<%= button_to "Crear una vista nueva", new_admin_collection_view_path, {method: :get } %>
</div>

<br><br>

<% @views.each do |view| %>

 <div class="view">
 
   <div class="view_header">
     <h3><center><%=view.name%></center</h3>
   </div>
     
       <div class="photos_view">
	 <h4><center>Fotos (<%= view.number_of_photos%>)</center></h4>
         <% view.photos.each do |photo| %>
         <img src="<%=photo.path_to_image%>"> 
         <br><br>
       <% end %>
       </div>

  <div class="view_properties">
    
   
      <%= link_to 'Mostrar', admin_collection_view_path(view), { method: :get} %>
  
    <br><br>
   
       <%= link_to 'Editar', edit_admin_collection_view_path(view), { method: :get}%>
   
    <br><br>
   
       <%= link_to 'Destruir', admin_collection_view_path(view),
                                   method: :delete,
                                   data: { confirm: 'Estas seguro?' } %> 
   
    
  </div>
</div>
<% end %>

</body>

app/views/admin/collection_views/new.html.erb
<body>

<%= link_to 'Vuelta a Admin', admin_root_path %>
<%= form_for :collection_view, url: admin_collection_views_path, method: "POST" do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label "Tipo de vista"  %>
    <br>
    <% @TYPES.each do |type| %>
    <%= f.radio_button :type, type %>
    <%= f.label :view_type, type, :value => type %>
    <br>
    <% end %>
  </p>
  <p>
    <%= f.submit "Crear vista" %>
  </p>
<% end %>

</body>

app/views/admin/collection_views/show.html.erb
<head> 
<style>

<!-- commented css for slideshow (jplugin cycle)
<style type "text/css">
.route {  
    height:  232px;  
    width:   232px;  
    padding: 0;  
    margin:  0;  
} 
 
.route img {  
    padding: 15px;  
    border:  1px solid #ccc;  
    background-color: #eee;  
    width:  200px; 
    height: 200px; 
    top:  0; 
    left: 0 
}
!-->

.picture{
          border:  2px solid #000000;
          width:   200px; 
          height:  200px;
         
}

.picture img{
             float: left;
             border:  2px solid #000000;
             width:   200px;
             heigth:  200px;
             margin:  1px;
}

</style>
</head>

<body>

<h1><center> Fotos en vista "<%= @this_view.name %>"</center></h1> <br>
<h4><%= link_to 'Vuelta Indice Vistas', admin_collection_views_path %></h4>

<% if @photos.empty?%> 
  <h2><center> No hay fotos en esta vista todavia</center><h2>

<% else %>
  <%@photos.each do |photo|%>
 
    <!-- Make the div clickable (link_to accepts blocks)!-->
    <%= link_to edit_admin_collection_photo_path(photo) do  %>
       <div class="picture">
    
       <img src="<%=photo.path_to_image%>"/>
    
       </div>
    <% end %>

  <% end %>

<% end %>

<!-- Slideshow with cycle

<div align="center">
<div class="nav"><a id="prev" href="#">Prev</a> <a id="next" href="#">Next</a></div>
<div class="route"> 
  <%@photos.each do |slide|%>
  <img src="/sample/<%=slide.name%>" height="200" width="200">
  <%end%> 
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('.route').cycle({
       fx:     'scrollHorz',
       prev:   '#prev',
       next:   '#next',
       timeout: 0,
       rev: true
    });
  });
</script>

</div>
!-->

</body>