config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  
  namespace :admin do
    
    root 'welcome#index'
     
    resources :collection_photos do 
                 collection do
                   get 'archive' => 'collection_photos#index_archive' 
                   get 'edit_batch' => 'collection_photos#edit_batch' 
                   put 'edit_batch' => 'collection_photos#update_batch'  
                 end
              end
    resources :collection_views, :collection_tags
  end
  
  

end

app/models/collection_photo.rb
class CollectionPhoto < ActiveRecord::Base

### TAGGINGS

# keywords' context maps to column 'keyword' of collection_tag table 
acts_as_taggable_on :keywords, 
                    :properties

### CLASS METHODS

def CollectionPhoto.types

# types of collection_photos:
#                            - unclassified = new added photos
#                            - archive      = personal collection
#                            - portfolio    = project photo
#                            - none       = default option to be shown 
['none', 'archive', 'portfolio', 'unclassified']

end


def CollectionPhoto.properties

  # values of context 'properties'
  ['public', 'new']

end

# returns an array of common keywords
def CollectionPhoto.find_join_keywords_of photo_batch 

  join_keywords= photo_batch.first.keyword_list
  photo_batch.each {|photo| join_keywords = join_keywords & photo.keyword_list }
  
  join_keywords
end


### INSTANCE MEHTODS

def path_to_image

  # constant defined in config/initializers/constants.rb
  path_to_image = "#{COLLECTION_FOLDER_PATH}/" << self.name  

end

end

app/controllers/admin/collection_photos_controller.rb
class Admin::CollectionPhotosController < ApplicationController

# Photos are tagged with keywords (from collection_tags table) 
# This allows to render partial and disjoint (covers) views of 
# the collection.

def new 

end

def index

  redirect_to archive_admin_collection_photos_path
 
end

# GET 'admin/collection_photos'
#
# index with filter capabilities
def index_archive
  
  @all_collection_tags = CollectionTag.all
  @PROPERTIES = CollectionPhoto.properties
  
  # show either photos filtered by (keywords and/or properties) or all
  @keywords_filter  = []
  @properties_filter = []
  
  if params[:filter_by_keywords]
    @keywords_filter = params[:filter_by_keywords]
    photos_by_keywords = CollectionPhoto.tagged_with(@keywords_filter, :on => :keywords, :any => true)
  else photos_by_keywords = CollectionPhoto.where(collection_type: 'archive') 
  end
  
  if params[:filter_by_properties]
    @properties_filter = params[:filter_by_properties]
    photos_by_properties = CollectionPhoto.tagged_with(@properties_filter, :on => :properties, :match_any => true)
  else photos_by_properties = CollectionPhoto.where(collection_type: 'archive')
  end
  @photos = photos_by_keywords & photos_by_properties
  render "index"
#render plain: params.inspect
end


# 'GET admin/collection_photos/:id'
def show
    
    @photo = CollectionPhoto.find(params[:id])
    
end

# 'POST ''admin/collection_photos'
def create
    
  photo = CollectionPhoto.new(photo_params)
  
  photo.save!
  
  redirect_to admin_collection_photo_path(photo)
  
end

# GET 'admin/collection_photos/:id/edit'
def edit
  
  @photo = CollectionPhoto.find(params[:id])
  @available_tags = CollectionTag.all
  @TYPES = CollectionPhoto.types
  @PROPERTIES = CollectionPhoto.properties
end

# PATCH/PUT 'admin/collection_photos/:id'
#
# adds and/or remove keywords to collection_photo in params[:id]
# first remove then add (removing and adding a keywords untouches it)
def update

  photo = CollectionPhoto.find(params[:id])
  
  
  #photo.keyword_list.remove(params[:keywords_to_delete]) if params[:keywords_to_delete]

  #photo.keyword_list.add(params[:keywords_to_append])    if params[:keywords_to_append]
  
  photo.keyword_list = params[:keyword_list]
  photo.property_list = params[:property_list]
  photo.collection_type = params[:collection_photo][:collection_type]
  
  photo.save!
  photo.reload
 
  redirect_to edit_admin_collection_photo_path(photo)
  #render plain: params.inspect
end

# "GET 'admin/collection_photos/edit_batch'
def edit_batch

  if params[:photos_to_tag_ids]
    @batch = CollectionPhoto.find(params[:photos_to_tag_ids])
  else
    @batch = CollectionPhoto.find(params[:filtered_index_ids])
  end
  
  @collection_tags = CollectionTag.all
  @PROPERTIES = CollectionPhoto.properties
  
  # find join tags (so we can batch-delete them if wanted to)
  @join_keywords = CollectionPhoto.find_join_keywords_of(@batch)
  
end

# PUT 'admin/collection_photos/'
def update_batch
  
  if params[:photo_batch_ids]
    
    photos = CollectionPhoto.find(params[:photo_batch_ids])
    
    #delete keywords
    if params[:keywords_to_delete] 
      photos.each { |photo| photo.keyword_list.remove(params[:keywords_to_delete]) }
    end
    
    #add keywords
    if  params[:keywords_to_append]
      photos.each { |photo| photo.keyword_list.add(params[:keywords_to_append]) }
    end
    
    #delete properties
    if params[:properties_to_delete]
      photos.each { |photo| photo.property_list.remove(params[:properties_to_delete]) }
    end

    #add properties
    if params[:properties_to_append]
       photos.each { |photo| photo.property_list.add(params[:properties_to_append]) }    
    end

    # reload records
    photos.each do |photo|
      photo.save!
      photo.reload
    end
  end
  
  redirect_to admin_collection_photos_path
end

# DELETE 'admin/collection_photos/:id'
def destroy
  
  #@photo=CollectionPhoto.find(params[:id])
  #@photo.destroy
  #redirect_to collection_photos_path
  render plain: "action to be implemented"
end


private

def photo_params 
# whitelists attributes
# 'name' CollectionPhoto model
# 'tag_list' of Tag model
  
  params.require(:collection_photo).permit(:name, :tag_list)
  
end


end

app/controllers/collection_photos_controller.rb
class CollectionPhotosController < ApplicationController

# Uses tags to generate partial and covering (disjoint) views of 
# the collection.
#
# The list of keywords are those from model CollectionTag
#

def new 

end

def index
  
  @all_tags = CollectionTag.all
  @ftags = []
  
  # show only photos filtered by tags,
  # and make the filter available to the view
  if params[:filter_by_tags_ids]
    
    params[:filter_by_tags_ids].each { |id| @ftags << id.to_i  }
    
    keywords = get_keywords(params[:filter_by_tags_ids])
    
    @photos = CollectionPhoto.tagged_with(keywords, :on => :keywords, :math_all => true)
    
  else @photos = CollectionPhoto.all  
  end

end

  
def show
    
    @photo = CollectionPhoto.find(params[:id])
    
end

def create
    
  @photo = CollectionPhoto.new(photo_params)
  
  @photo.save
  
  redirect_to @photo
  
end

def edit
  
  @photo = CollectionPhoto.find(params[:id])
  @available_tags = CollectionTag.all

end

# either tag params[:id] with collection_tags 
# whose ids are given in params[:tag_with_ids]
#
# or delete tags from params[:id] whose
# names are given in params[:delete_tag_ids]

def update

  photo = CollectionPhoto.find(params[:id])
  
  # first remove then add (removing and adding a tag untouches it)
  if params[:delete_tags_ids]
    
    keywords = get_keywords(params[:delete_tags_ids])
    photo.keyword_list.remove(keywords)
      
  end
  
  if params[:tag_with_ids]
  
    keywords = get_keywords(params[:tag_with_ids])
    photo.keyword_list.add(keywords)
 
  end
  
  photo.save
  photo.reload
  redirect_to edit_collection_photo_path(photo)

end


def destroy
  
  @photo=CollectionPhoto.find(params[:id])
  @photo.destroy
  redirect_to collection_photos_path
  
end


private

def photo_params 
# whitelists attributes
# 'name' CollectionPhoto model
# 'tag_list' of Tag model
  
  params.require(:collection_photo).permit(:name, :tag_list)
  
end


def get_keywords ids
  tags = CollectionTag.find(ids)
  keywords = []
  tags.each { |tag| keywords << tag.keyword }
  keywords
end
end

app/helpers/collection_photos_helper.rb
module CollectionPhotosHelper
end

app/views/admin/collection_photos/edit.html.erb
<head>
<style>
#photo{
              border:2px solid #009900;
              float:left;
              top: 20px;
              height:400px;
              width:33%;
              clear:left
}

#photo img {
   height: 100%;
   width: 100%;
}

#delete_tags{
           border: 2px solid #0000FF;
           width:33%;
           height:400px;
           float:right;
           overflow-y:scroll; 
}
#add_tags{
           border: 2px solid #0000FF;
           width:33%;
           height:400px;
           float:right;
           overflow-y:scroll;
}
#submit{
        width:100%;  
        text-align:right;
        margin-bottom:10px;
        margin-top:10px; 
        clear:both}
 
</style>
</head>


<body>

<h1><center> Editar Foto <%= @photo.name%> </center></h1>
<%= link_to 'Vuelta a Indice', admin_collection_photos_path %>
<br><br>

<%= form_for @photo, url: {action: "update"}, method: "PUT" do |f| %>

     <div id="submit">
       <%= f.submit "Actualizar foto"  %>
     </div>

     <div id="delete_tags">
        <h4><center> Propiedades:</center></h4>      
	    
              <% @PROPERTIES.each do |property| %>
	         
	         <ul>
		 <%= check_box_tag 'property_list[]', property, @photo.property_list.include?(property) -%>
		 <%= property %>
		 </ul>  

              <% end %>   
   
     </div>
   
     <div id="photo">
       
       <img src="<%=@photo.path_to_image%>"%>
       <br><br>
        <%= f.label "Nombre:"  %>
        <%= f.text_field :name %>
	<br>
	<%= f.label "Tipo:"  %>
        <%= f.select :collection_type, @TYPES %>

     </div>
   
     <div id="delete_tags">

       <h4><center> Keywords:</center></h4> 
       
       <% if @available_tags.empty? %> No keywords known
       
       <% else %>
          <% @available_tags.each do |tag| %>
	      <ul>
		<%= check_box_tag 'keyword_list[]', tag.keyword, @photo.keyword_list.include?(tag.keyword) -%>
		<%= tag.keyword -%>
	      </ul>
	      <% end %> 
       <% end %>

     </div>
     
<% end %>


</body>

app/views/admin/collection_photos/edit_batch.html.erb
<head>
<style>
#photo_batch{
              border:2px solid #009900;
              float:left;
              width:35%;
              margin-right:10px;
              top: 20px;
              height:600px;
              overflow-y:scroll;
              clear:left
}
#delete_tags{
           border: 2px solid #0000FF;
           width:30%;
           height:600px;
           float:right;
           margin-right:10px;
           overflow-y:scroll;
}
#add_tags{
           border: 2px solid #0000FF;
           width:30%;
           height:600px;
           margin-right:10px;
           float:right;
           overflow-y:scroll;
}
#submit{
        width:100%;  
        text-align:right;
        margin-bottom:10px;
        margin-top:10px; 
        clear:both}

</style>
</head>
<body>

<h4><%= link_to 'Vuelta a Indice', admin_collection_photos_path %></h4>

<%= form_tag({controller: "collection_photos", action: "update_batch"}, method: "PUT") do %>

<div id="submit">
<%= submit_tag 'Actualizar' %>
</div>

<div id="photo_batch">
  
  <h4> Batch:</h4>
  
  <% @batch.each do |photo| %>
    <img src="<%=photo.path_to_image%>", WIDTH=25%, HEIGHT=25%> 
    <%= photo.name %>
    <%= hidden_field_tag 'photo_batch_ids[]', photo.id%>
    <br><br>
  <% end %>
</div>

<div id="delete_tags">

  <h4> Selecciona propiedad para ANADIR a todas las fotos </h4> 
  <ul>
   <% @PROPERTIES.each do |property| %>
     <li> <%= check_box_tag 'properties_to_append[]', property %> 
          <%= property %> 
     </li>
   <% end %>
   </ul>

  <h4> Selecciona propiedad para ELIMINAR de todas las fotos </h4> 
  <ul>
   <% @PROPERTIES.each do |property| %>
     <li> <%= check_box_tag 'properties_to_delete[]', property %> 
          <%= property %> 
     </li>
   <% end %>
   </ul>
  
  
</div>

<div id="add_tags">

 <h4><center>Selecciona keyword para ANADIR</center></h4>
  <ul>
  <% @collection_tags.each do |tag| %>
  <li>
    <%= check_box_tag 'keywords_to_append[]', tag.keyword %> 
    <%= tag.keyword %>
  </li>
  <% end %>
  </li>


  <h4><center>Selecciona keywords para ELIMINAR</center></h4> 

  <% if @join_keywords.empty? %>
     No hay keywords comunes
  <% else %>
  (mostrando keywords comunes a todas las fotos):
  <br><br>
  <ul>
   <% @join_keywords.each do |keyword| %>
     <li> <%= check_box_tag 'keywords_to_delete[]', keyword %> 
          <%= keyword %> 
     </li>
   <% end %>
   </ul>
  <% end %>

</div>

<% end %>


</body>

app/views/admin/collection_photos/index.html.erb
<head>
<style>

#index_photos{
              border:2px solid #009900;
              float:left;
              margin-right:10px;
              top: 20px;
              height:600px;
              overflow-y:scroll;
              clear:left
}
#filter_by{
           border: 2px solid #0000FF;
           width:30%;
           height:600px;
           float:right;
           overflow-y:scroll;
}

#submit_filter{
               border: 2px solid #FF0000; 
               position: absoute;
               
               clear:both <!-- clear  !-->
}

#submit_edit_batch{
            border: 2px solid #FF0000; 
            margin-bottom:10px;
            float:left;
            clear:both <!-- clear  !-->
}

</style>
</head>

<body>


  <h1><center>Archivo de Fotos</center></h1>
  
  <%= link_to 'Vuelta a Admin', admin_root_path %>
  <br><br>
  
  
    
     <%= form_tag({controller: "collection_photos", action: "edit_batch"}, method: "GET") do %>

       <div id="submit_edit_batch">
        <%= submit_tag "Editar fotos seleccionadas (o todas)" %>
	<%= hidden_field_tag 'collection_type', @TYPE  %>
       </div>
       
      <div id="index_photos">
      
        <table>
	
	  <% @photos.each do |photo| %>
	
	   <tr>
	     <td><img src="<%=photo.path_to_image%>", WIDTH=200, HEIGHT=200> </td>
	     <td><%=photo.name%></td>
	     <td></td><td></td>
	     <td><%= link_to 'Mostrar', admin_collection_photo_path(photo) %></td>
       	     <td><%= link_to 'Editar', edit_admin_collection_photo_path(photo)%></td>
	     <td><%= link_to 'Destruir', admin_collection_photo_path(photo),
		  method: :delete,
		  data: { confirm: 'Are you sure?' } %></td>
	  
	     <td>Keywords:
	     <% if !photo.keywords.any?%> 
	       ninguno
	    
	     <% else %>
	      
	        <% photo.keywords.each do |keyword| %>
	      
	           <%= keyword.name %>
		
	        <% end %>
	    
             <% end %>
	     </td>
	   </tr>
	   
	  <tr>
	   <td> <%= check_box_tag 'photos_to_tag_ids[]', photo.id %>  Seleccionar para batch-edit</td>
	   <%= hidden_field_tag 'filtered_index_ids[]', photo.id  %>
	  </tr>
	  
	  <% end %>
	
      </table>
      
    </div>
     
   <% end %>

    <div id="filter_by">
      <h4>Keywords:</h4>

      <%= form_tag(admin_collection_photos_path, method: "GET") do %>
      
         <% @all_collection_tags.each do |tag| %>
	   <ul>
	     <%= check_box_tag 'filter_by_keywords[]', tag.keyword, @keywords_filter.include?(tag.keyword)%>
	    <%= tag.keyword %>
	  </ul> 
	 <% end %>
	 
	 <h4>Propiedades:</h4>
	 <% @PROPERTIES.each do |property| %>
	   <ul>
	     <%= check_box_tag 'filter_by_properties[]', property, @properties_filter.include?(property)%>
	    <%= property %>
	  </ul> 
	 <% end %>
      
	 <%= submit_tag "filtrar (any)" %>
	 <%= hidden_field_tag 'collection_type', @TYPE  %>
      <% end %>
      
    </div>

</body>

app/views/admin/collection_photos/new.html.erb
<body>
<%= form_for :collection_photo, url: admin_collection_photos_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

</body>

app/views/admin/collection_photos/show.html.erb
<body>

<%= link_to 'Back to Index of Photos', admin_collection_photos_path %>
<br><br>
<img src="<%=@photo.path_to_image%>", WIDTH=90%, HEIGHT=90%>
<%=@photo.path_to_image%>
</body>

app/views/admin/collection_photos/slideshow.html.erb
<h1> Slide show:</h1>
<%= link_to 'Back to Home', welcome_index_path %>

<style type "text/css">
.route {  
    height:  232px;  
    width:   232px;  
    padding: 0;  
    margin:  0;  
} 
 
.route img {  
    padding: 15px;  
    border:  1px solid #ccc;  
    background-color: #eee;  
    width:  200px; 
    height: 200px; 
    top:  0; 
    left: 0 
}
</style>
<div align="center">
<div class="nav"><a id="prev" href="#">Prev</a> <a id="next" href="#">Next</a></div>
<div class="route"> 
  <%@route.each do |slide|%>
  <img src="/sample/<%=slide.name%>" height="200" width="200">
  <%end%> 
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('.route').cycle({
       fx:     'scrollHorz',
       prev:   '#prev',
       next:   '#next',
       timeout: 0,
       rev: true
    });
  });
</script>

</div>