config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  
  namespace :admin do
    
    root 'welcome#index'
     
    resources :collection_photos do 
                 collection do
                   get 'archive' => 'collection_photos#index_archive' 
                   get 'edit_batch' => 'collection_photos#edit_batch' 
                   put 'edit_batch' => 'collection_photos#update_batch'  
                 end
              end
    resources :collection_views, :collection_tags
  end
  
  

end

app/models/collection_tag.rb
class CollectionTag < ActiveRecord::Base


### ASSOCIATIONS
has_and_belongs_to_many :collection_views, 
                        join_table: "collection_tags_views" 


#### CALLBACKS
before_destroy :clear_associated_views
before_destroy :untag_photos



### INSTANCE METHODS

def clear_associated_views
  
  self.collection_views.clear

end

# return any collection_photo record tagged with tag keyword
def tagged_photos

 CollectionPhoto.tagged_with(self.keyword, :on => :keywords, :any => true)

end

def untag_photos
  
  photos = self.tagged_photos

  if self.tagged_photos.any? 
    
    self.tagged_photos.each do |photo| 
      
      photo.keyword_list.remove(self.keyword) 
      photo.save!
      photo.reload   
      
    end
  end

  self
end

# retags photos under tag's keyword 
# with new given keyword
def rename_keyword renamed_keyword
  
  photos = self.tagged_photos
  
  if photos.any? 
    
    photos.each do |photo|
      
      photo.keyword_list.remove(self.keyword) 
      photo.keyword_list.add(renamed_keyword)
      photo.save!
      photo.reload
    end
  end
  
  self[:keyword] = renamed_keyword
  self.save!
end


  
end

app/controllers/admin/collection_tags_controller.rb
class Admin::CollectionTagsController < ApplicationController

# GET '/admin/collection_tags'
def index 

  @current_keywords = CollectionTag.all

end

def create

  tag = CollectionTag.new(tag_params)  
  tag.save
  
  # render index of tags
  redirect_to admin_collection_tags_path

end

# GET '/admin/collection_tags/:id'
def edit
  @tag = set_tag
  # render form
  
end

# PATCH/PUT 'admin/collection_tags/:id'
#
# renames a tag's keyword updating
# photos tagged under old keyword's name
def update

  this_tag = set_tag
  
  new_keyword = params[:collection_tag][:keyword]
  this_tag.rename_keyword(new_keyword)  if !new_keyword.empty? 
  
  redirect_to admin_collection_tags_path
end

def destroy

this_tag = set_tag

# callback methods: 
#                  - untag_photos (save & reload untagged photos)
#                  - remove_from_views
#
this_tag.destroy

# 
redirect_to admin_collection_tags_path

end

private

#whitelists attribute 'keyword' of CollectionTag
def tag_params 
  
  params.require(:collection_tag).permit(:keyword)
  
end

def set_tag

 CollectionTag.find(params[:id])

end

end

app/helpers/collection_tags_helper.rb
module CollectionTagsHelper
end

app/views/collection_tags/index.html.erb
<!DOCTYPE html>
<html>
<body>
<%= link_to 'Back to Home', welcome_index_path %>
<h1><center> Index of Keywords </center></h1>
<br><br>

<div style="width: 100%;overflow:auto;">
    
  <div align="left" style="float:left; width: 80%">
     <%= form_for :collection_tag, url: collection_tags_path do |f| %>
  <p>
    <%= f.label :new_keyword %><br>
    <%= f.text_field :keyword %>
  </p>
 
  <p>
    <%= f.submit "Create tag" %>
  </p>
<% end %>
      
    </div>
    <div align="right" style="float:right;">
      
      <h2>Existing keywords: </h2>
      <br>
      <% if @current_keywords.empty? %> No keywords known
      <% else %>
        <% @current_keywords.each do |tag| %>
          <%=tag.keyword %> 
          <br>
        <% end %>
      <% end %>
    
</div>
    
</body>
</html>